name: Create Release

on:
  workflow_dispatch:

permissions: 
  write-all

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build Application
      run: |
        pip install PyInstaller
        pip install Eel
        python -m eel spells.py frontend --onefile --noconsole
        Xcopy /E /I json dist\json
    - name: version
      run: echo "::set-output name=version::$(type version.txt)"
      id: version
    - name: zip release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        path: ./dist/*
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.version.outputs.version }}
        tag: ${{ steps.version.outputs.version }}
        body: ${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
